// apps/react-demo/src/pages/ProductList/ProductList.tsx
import type { PaginatedResponse, Producto } from '@ngr-inventory/api-contracts';
import React, { useState, useEffect } from 'react';

import styles from './ProductList.module.scss';

// Componente que muestra la lista de productos obtenida desde la API
export default function ProductList(): React.JSX.Element {
  const [productos, setProductos] = useState<Producto[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Carga productos desde la API (interceptada por MSW en desarrollo)
    fetch('/api/productos')
      .then((r) => r.json())
      .then((data: PaginatedResponse<Producto>) => {
        setProductos(data.data);
      })
      .catch(console.error)
      .finally(() => {
        setLoading(false);
      });
  }, []);

  if (loading) {
    return <p className="text-muted">Cargando productos...</p>;
  }

  if (productos.length === 0) {
    return <p className="text-muted">No se encontraron productos.</p>;
  }

  return (
    <div className={styles['container']}>
      <table className="table table-striped" aria-label="Lista de productos">
        <thead>
          <tr>
            <th scope="col">Código</th>
            <th scope="col">Nombre</th>
            <th scope="col">Categoría</th>
            <th scope="col">Stock mínimo</th>
          </tr>
        </thead>
        <tbody>
          {productos.map((p) => (
            <tr key={p.id}>
              <td>{p.codigo}</td>
              <td>{p.nombre}</td>
              <td>{p.categoriaNombre}</td>
              <td>{p.stockMinimo}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// apps/angular-demo/src/app/pages/product-list/product-list.component.ts
import { NgFor, NgIf } from '@angular/common';
import { Component, type OnInit, signal } from '@angular/core';
import type { PaginatedResponse, Producto } from '@ngr-inventory/api-contracts';

// Componente que muestra la lista de productos obtenida desde la API
@Component({
  selector: 'app-product-list',
  standalone: true,
  imports: [NgIf, NgFor],
  template: `
    <p *ngIf="loading()">Cargando productos...</p>
    <p *ngIf="!loading() && productos().length === 0" class="text-muted">
      No se encontraron productos.
    </p>
    <table
      *ngIf="!loading() && productos().length > 0"
      class="table table-striped"
      aria-label="Lista de productos"
    >
      <thead>
        <tr>
          <th scope="col">Código</th>
          <th scope="col">Nombre</th>
          <th scope="col">Categoría</th>
          <th scope="col">Stock mínimo</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let p of productos()">
          <td>{{ p.codigo }}</td>
          <td>{{ p.nombre }}</td>
          <td>{{ p.categoriaNombre }}</td>
          <td>{{ p.stockMinimo }}</td>
        </tr>
      </tbody>
    </table>
  `,
})
export class ProductListComponent implements OnInit {
  // Señales para estado reactivo
  readonly productos = signal<Producto[]>([]);
  readonly loading = signal(true);

  ngOnInit(): void {
    // Carga productos desde la API (interceptada por MSW en desarrollo)
    void fetch('/api/productos')
      .then((r) => r.json() as Promise<PaginatedResponse<Producto>>)
      .then((data) => {
        this.productos.set(data.data);
      })
      .catch(console.error)
      .finally(() => {
        this.loading.set(false);
      });
  }
}
